//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TSTModel", "FK_3TEmployees_3TDepartments", "C3TDepartments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TSTModel.C3TDepartments), "C3TEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.C3TEmployees), true)]
[assembly: EdmRelationshipAttribute("TSTModel", "FK_3TRequests_3TEmployees", "C3TEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TSTModel.C3TEmployees), "C3TRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.C3TRequests), true)]
[assembly: EdmRelationshipAttribute("TSTModel", "FK_3TRequests_3TEmployees1", "C3TEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TSTModel.C3TEmployees), "C3TRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.C3TRequests), true)]
[assembly: EdmRelationshipAttribute("TSTModel", "FK_3TRequests_3TRequestStatuses", "C3TRequestStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TSTModel.C3TRequestStatuses), "C3TRequests", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TSTModel.C3TRequests), true)]

#endregion

namespace TSTModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TSTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TSTEntities object using the connection string found in the 'TSTEntities' section of the application configuration file.
        /// </summary>
        public TSTEntities() : base("name=TSTEntities", "TSTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSTEntities object.
        /// </summary>
        public TSTEntities(string connectionString) : base(connectionString, "TSTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TSTEntities object.
        /// </summary>
        public TSTEntities(EntityConnection connection) : base(connection, "TSTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C3TDepartments> C3TDepartments
        {
            get
            {
                if ((_C3TDepartments == null))
                {
                    _C3TDepartments = base.CreateObjectSet<C3TDepartments>("C3TDepartments");
                }
                return _C3TDepartments;
            }
        }
        private ObjectSet<C3TDepartments> _C3TDepartments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C3TEmployees> C3TEmployees
        {
            get
            {
                if ((_C3TEmployees == null))
                {
                    _C3TEmployees = base.CreateObjectSet<C3TEmployees>("C3TEmployees");
                }
                return _C3TEmployees;
            }
        }
        private ObjectSet<C3TEmployees> _C3TEmployees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C3TRequests> C3TRequests
        {
            get
            {
                if ((_C3TRequests == null))
                {
                    _C3TRequests = base.CreateObjectSet<C3TRequests>("C3TRequests");
                }
                return _C3TRequests;
            }
        }
        private ObjectSet<C3TRequests> _C3TRequests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C3TRequestStatuses> C3TRequestStatuses
        {
            get
            {
                if ((_C3TRequestStatuses == null))
                {
                    _C3TRequestStatuses = base.CreateObjectSet<C3TRequestStatuses>("C3TRequestStatuses");
                }
                return _C3TRequestStatuses;
            }
        }
        private ObjectSet<C3TRequestStatuses> _C3TRequestStatuses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C3TDepartments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC3TDepartments(C3TDepartments c3TDepartments)
        {
            base.AddObject("C3TDepartments", c3TDepartments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C3TEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC3TEmployees(C3TEmployees c3TEmployees)
        {
            base.AddObject("C3TEmployees", c3TEmployees);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C3TRequests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC3TRequests(C3TRequests c3TRequests)
        {
            base.AddObject("C3TRequests", c3TRequests);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C3TRequestStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC3TRequestStatuses(C3TRequestStatuses c3TRequestStatuses)
        {
            base.AddObject("C3TRequestStatuses", c3TRequestStatuses);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="C3TDepartments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C3TDepartments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C3TDepartments object.
        /// </summary>
        /// <param name="departmentId">Initial value of the DepartmentId property.</param>
        /// <param name="departmentName">Initial value of the DepartmentName property.</param>
        public static C3TDepartments CreateC3TDepartments(global::System.Int32 departmentId, global::System.String departmentName)
        {
            C3TDepartments c3TDepartments = new C3TDepartments();
            c3TDepartments.DepartmentId = departmentId;
            c3TDepartments.DepartmentName = departmentName;
            return c3TDepartments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentId
        {
            get
            {
                return _DepartmentId;
            }
            set
            {
                if (_DepartmentId != value)
                {
                    OnDepartmentIdChanging(value);
                    ReportPropertyChanging("DepartmentId");
                    _DepartmentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentId");
                    OnDepartmentIdChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentId;
        partial void OnDepartmentIdChanging(global::System.Int32 value);
        partial void OnDepartmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentDescription
        {
            get
            {
                return _DepartmentDescription;
            }
            set
            {
                OnDepartmentDescriptionChanging(value);
                ReportPropertyChanging("DepartmentDescription");
                _DepartmentDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentDescription");
                OnDepartmentDescriptionChanged();
            }
        }
        private global::System.String _DepartmentDescription;
        partial void OnDepartmentDescriptionChanging(global::System.String value);
        partial void OnDepartmentDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TEmployees_3TDepartments", "C3TEmployees")]
        public EntityCollection<C3TEmployees> C3TEmployees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<C3TEmployees>("TSTModel.FK_3TEmployees_3TDepartments", "C3TEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<C3TEmployees>("TSTModel.FK_3TEmployees_3TDepartments", "C3TEmployees", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="C3TEmployees")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C3TEmployees : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C3TEmployees object.
        /// </summary>
        /// <param name="employeeId">Initial value of the EmployeeId property.</param>
        /// <param name="empTitle">Initial value of the EmpTitle property.</param>
        /// <param name="empFirstName">Initial value of the EmpFirstName property.</param>
        /// <param name="empLastName">Initial value of the EmpLastName property.</param>
        /// <param name="empIsActive">Initial value of the EmpIsActive property.</param>
        /// <param name="empDeptId">Initial value of the EmpDeptId property.</param>
        public static C3TEmployees CreateC3TEmployees(global::System.Int32 employeeId, global::System.String empTitle, global::System.String empFirstName, global::System.String empLastName, global::System.Boolean empIsActive, global::System.Int32 empDeptId)
        {
            C3TEmployees c3TEmployees = new C3TEmployees();
            c3TEmployees.EmployeeId = employeeId;
            c3TEmployees.EmpTitle = empTitle;
            c3TEmployees.EmpFirstName = empFirstName;
            c3TEmployees.EmpLastName = empLastName;
            c3TEmployees.EmpIsActive = empIsActive;
            c3TEmployees.EmpDeptId = empDeptId;
            return c3TEmployees;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeId
        {
            get
            {
                return _EmployeeId;
            }
            set
            {
                if (_EmployeeId != value)
                {
                    OnEmployeeIdChanging(value);
                    ReportPropertyChanging("EmployeeId");
                    _EmployeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeId");
                    OnEmployeeIdChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeId;
        partial void OnEmployeeIdChanging(global::System.Int32 value);
        partial void OnEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpTitle
        {
            get
            {
                return _EmpTitle;
            }
            set
            {
                OnEmpTitleChanging(value);
                ReportPropertyChanging("EmpTitle");
                _EmpTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpTitle");
                OnEmpTitleChanged();
            }
        }
        private global::System.String _EmpTitle;
        partial void OnEmpTitleChanging(global::System.String value);
        partial void OnEmpTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpFirstName
        {
            get
            {
                return _EmpFirstName;
            }
            set
            {
                OnEmpFirstNameChanging(value);
                ReportPropertyChanging("EmpFirstName");
                _EmpFirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpFirstName");
                OnEmpFirstNameChanged();
            }
        }
        private global::System.String _EmpFirstName;
        partial void OnEmpFirstNameChanging(global::System.String value);
        partial void OnEmpFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmpLastName
        {
            get
            {
                return _EmpLastName;
            }
            set
            {
                OnEmpLastNameChanging(value);
                ReportPropertyChanging("EmpLastName");
                _EmpLastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmpLastName");
                OnEmpLastNameChanged();
            }
        }
        private global::System.String _EmpLastName;
        partial void OnEmpLastNameChanging(global::System.String value);
        partial void OnEmpLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpPhotoUrl
        {
            get
            {
                return _EmpPhotoUrl;
            }
            set
            {
                OnEmpPhotoUrlChanging(value);
                ReportPropertyChanging("EmpPhotoUrl");
                _EmpPhotoUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpPhotoUrl");
                OnEmpPhotoUrlChanged();
            }
        }
        private global::System.String _EmpPhotoUrl;
        partial void OnEmpPhotoUrlChanging(global::System.String value);
        partial void OnEmpPhotoUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpPhone
        {
            get
            {
                return _EmpPhone;
            }
            set
            {
                OnEmpPhoneChanging(value);
                ReportPropertyChanging("EmpPhone");
                _EmpPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpPhone");
                OnEmpPhoneChanged();
            }
        }
        private global::System.String _EmpPhone;
        partial void OnEmpPhoneChanging(global::System.String value);
        partial void OnEmpPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpEmail
        {
            get
            {
                return _EmpEmail;
            }
            set
            {
                OnEmpEmailChanging(value);
                ReportPropertyChanging("EmpEmail");
                _EmpEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpEmail");
                OnEmpEmailChanged();
            }
        }
        private global::System.String _EmpEmail;
        partial void OnEmpEmailChanging(global::System.String value);
        partial void OnEmpEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EmpHireDate
        {
            get
            {
                return _EmpHireDate;
            }
            set
            {
                OnEmpHireDateChanging(value);
                ReportPropertyChanging("EmpHireDate");
                _EmpHireDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpHireDate");
                OnEmpHireDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EmpHireDate;
        partial void OnEmpHireDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEmpHireDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpNotes
        {
            get
            {
                return _EmpNotes;
            }
            set
            {
                OnEmpNotesChanging(value);
                ReportPropertyChanging("EmpNotes");
                _EmpNotes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpNotes");
                OnEmpNotesChanged();
            }
        }
        private global::System.String _EmpNotes;
        partial void OnEmpNotesChanging(global::System.String value);
        partial void OnEmpNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EmpIsActive
        {
            get
            {
                return _EmpIsActive;
            }
            set
            {
                OnEmpIsActiveChanging(value);
                ReportPropertyChanging("EmpIsActive");
                _EmpIsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpIsActive");
                OnEmpIsActiveChanged();
            }
        }
        private global::System.Boolean _EmpIsActive;
        partial void OnEmpIsActiveChanging(global::System.Boolean value);
        partial void OnEmpIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpDeptId
        {
            get
            {
                return _EmpDeptId;
            }
            set
            {
                OnEmpDeptIdChanging(value);
                ReportPropertyChanging("EmpDeptId");
                _EmpDeptId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpDeptId");
                OnEmpDeptIdChanged();
            }
        }
        private global::System.Int32 _EmpDeptId;
        partial void OnEmpDeptIdChanging(global::System.Int32 value);
        partial void OnEmpDeptIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TEmployees_3TDepartments", "C3TDepartments")]
        public C3TDepartments C3TDepartments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TDepartments>("TSTModel.FK_3TEmployees_3TDepartments", "C3TDepartments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TDepartments>("TSTModel.FK_3TEmployees_3TDepartments", "C3TDepartments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<C3TDepartments> C3TDepartmentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TDepartments>("TSTModel.FK_3TEmployees_3TDepartments", "C3TDepartments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<C3TDepartments>("TSTModel.FK_3TEmployees_3TDepartments", "C3TDepartments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TRequests_3TEmployees", "C3TRequests")]
        public EntityCollection<C3TRequests> C3TRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<C3TRequests>("TSTModel.FK_3TRequests_3TEmployees", "C3TRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<C3TRequests>("TSTModel.FK_3TRequests_3TEmployees", "C3TRequests", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TRequests_3TEmployees1", "C3TRequests")]
        public EntityCollection<C3TRequests> C3TRequests1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<C3TRequests>("TSTModel.FK_3TRequests_3TEmployees1", "C3TRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<C3TRequests>("TSTModel.FK_3TRequests_3TEmployees1", "C3TRequests", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="C3TRequests")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C3TRequests : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C3TRequests object.
        /// </summary>
        /// <param name="reqId">Initial value of the ReqId property.</param>
        /// <param name="reqDate">Initial value of the ReqDate property.</param>
        /// <param name="reqTechNotes">Initial value of the ReqTechNotes property.</param>
        /// <param name="reqStatusId">Initial value of the ReqStatusId property.</param>
        /// <param name="reqEmployeeId">Initial value of the ReqEmployeeId property.</param>
        public static C3TRequests CreateC3TRequests(global::System.Int32 reqId, global::System.DateTime reqDate, global::System.String reqTechNotes, global::System.Int32 reqStatusId, global::System.Int32 reqEmployeeId)
        {
            C3TRequests c3TRequests = new C3TRequests();
            c3TRequests.ReqId = reqId;
            c3TRequests.ReqDate = reqDate;
            c3TRequests.ReqTechNotes = reqTechNotes;
            c3TRequests.ReqStatusId = reqStatusId;
            c3TRequests.ReqEmployeeId = reqEmployeeId;
            return c3TRequests;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReqId
        {
            get
            {
                return _ReqId;
            }
            set
            {
                if (_ReqId != value)
                {
                    OnReqIdChanging(value);
                    ReportPropertyChanging("ReqId");
                    _ReqId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ReqId");
                    OnReqIdChanged();
                }
            }
        }
        private global::System.Int32 _ReqId;
        partial void OnReqIdChanging(global::System.Int32 value);
        partial void OnReqIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReqDate
        {
            get
            {
                return _ReqDate;
            }
            set
            {
                OnReqDateChanging(value);
                ReportPropertyChanging("ReqDate");
                _ReqDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReqDate");
                OnReqDateChanged();
            }
        }
        private global::System.DateTime _ReqDate;
        partial void OnReqDateChanging(global::System.DateTime value);
        partial void OnReqDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReqCloseDate
        {
            get
            {
                return _ReqCloseDate;
            }
            set
            {
                OnReqCloseDateChanging(value);
                ReportPropertyChanging("ReqCloseDate");
                _ReqCloseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReqCloseDate");
                OnReqCloseDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReqCloseDate;
        partial void OnReqCloseDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReqCloseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReqTechNotes
        {
            get
            {
                return _ReqTechNotes;
            }
            set
            {
                OnReqTechNotesChanging(value);
                ReportPropertyChanging("ReqTechNotes");
                _ReqTechNotes = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReqTechNotes");
                OnReqTechNotesChanged();
            }
        }
        private global::System.String _ReqTechNotes;
        partial void OnReqTechNotesChanging(global::System.String value);
        partial void OnReqTechNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReqScreenCapture
        {
            get
            {
                return _ReqScreenCapture;
            }
            set
            {
                OnReqScreenCaptureChanging(value);
                ReportPropertyChanging("ReqScreenCapture");
                _ReqScreenCapture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ReqScreenCapture");
                OnReqScreenCaptureChanged();
            }
        }
        private global::System.String _ReqScreenCapture;
        partial void OnReqScreenCaptureChanging(global::System.String value);
        partial void OnReqScreenCaptureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReqStatusId
        {
            get
            {
                return _ReqStatusId;
            }
            set
            {
                OnReqStatusIdChanging(value);
                ReportPropertyChanging("ReqStatusId");
                _ReqStatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReqStatusId");
                OnReqStatusIdChanged();
            }
        }
        private global::System.Int32 _ReqStatusId;
        partial void OnReqStatusIdChanging(global::System.Int32 value);
        partial void OnReqStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReqEmployeeId
        {
            get
            {
                return _ReqEmployeeId;
            }
            set
            {
                OnReqEmployeeIdChanging(value);
                ReportPropertyChanging("ReqEmployeeId");
                _ReqEmployeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReqEmployeeId");
                OnReqEmployeeIdChanged();
            }
        }
        private global::System.Int32 _ReqEmployeeId;
        partial void OnReqEmployeeIdChanging(global::System.Int32 value);
        partial void OnReqEmployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ReqTechId
        {
            get
            {
                return _ReqTechId;
            }
            set
            {
                OnReqTechIdChanging(value);
                ReportPropertyChanging("ReqTechId");
                _ReqTechId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReqTechId");
                OnReqTechIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ReqTechId;
        partial void OnReqTechIdChanging(Nullable<global::System.Int32> value);
        partial void OnReqTechIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TRequests_3TEmployees", "C3TEmployees")]
        public C3TEmployees C3TEmployees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees", "C3TEmployees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees", "C3TEmployees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<C3TEmployees> C3TEmployeesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees", "C3TEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees", "C3TEmployees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TRequests_3TEmployees1", "C3TEmployees")]
        public C3TEmployees C3TEmployees1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees1", "C3TEmployees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees1", "C3TEmployees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<C3TEmployees> C3TEmployees1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees1", "C3TEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<C3TEmployees>("TSTModel.FK_3TRequests_3TEmployees1", "C3TEmployees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TRequests_3TRequestStatuses", "C3TRequestStatuses")]
        public C3TRequestStatuses C3TRequestStatuses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TRequestStatuses>("TSTModel.FK_3TRequests_3TRequestStatuses", "C3TRequestStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TRequestStatuses>("TSTModel.FK_3TRequests_3TRequestStatuses", "C3TRequestStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<C3TRequestStatuses> C3TRequestStatusesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<C3TRequestStatuses>("TSTModel.FK_3TRequests_3TRequestStatuses", "C3TRequestStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<C3TRequestStatuses>("TSTModel.FK_3TRequests_3TRequestStatuses", "C3TRequestStatuses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TSTModel", Name="C3TRequestStatuses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C3TRequestStatuses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C3TRequestStatuses object.
        /// </summary>
        /// <param name="requestStatusId">Initial value of the RequestStatusId property.</param>
        /// <param name="requestStatusName">Initial value of the RequestStatusName property.</param>
        public static C3TRequestStatuses CreateC3TRequestStatuses(global::System.Int32 requestStatusId, global::System.String requestStatusName)
        {
            C3TRequestStatuses c3TRequestStatuses = new C3TRequestStatuses();
            c3TRequestStatuses.RequestStatusId = requestStatusId;
            c3TRequestStatuses.RequestStatusName = requestStatusName;
            return c3TRequestStatuses;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RequestStatusId
        {
            get
            {
                return _RequestStatusId;
            }
            set
            {
                if (_RequestStatusId != value)
                {
                    OnRequestStatusIdChanging(value);
                    ReportPropertyChanging("RequestStatusId");
                    _RequestStatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RequestStatusId");
                    OnRequestStatusIdChanged();
                }
            }
        }
        private global::System.Int32 _RequestStatusId;
        partial void OnRequestStatusIdChanging(global::System.Int32 value);
        partial void OnRequestStatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestStatusName
        {
            get
            {
                return _RequestStatusName;
            }
            set
            {
                OnRequestStatusNameChanging(value);
                ReportPropertyChanging("RequestStatusName");
                _RequestStatusName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestStatusName");
                OnRequestStatusNameChanged();
            }
        }
        private global::System.String _RequestStatusName;
        partial void OnRequestStatusNameChanging(global::System.String value);
        partial void OnRequestStatusNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RequestStatusDescription
        {
            get
            {
                return _RequestStatusDescription;
            }
            set
            {
                OnRequestStatusDescriptionChanging(value);
                ReportPropertyChanging("RequestStatusDescription");
                _RequestStatusDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RequestStatusDescription");
                OnRequestStatusDescriptionChanged();
            }
        }
        private global::System.String _RequestStatusDescription;
        partial void OnRequestStatusDescriptionChanging(global::System.String value);
        partial void OnRequestStatusDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TSTModel", "FK_3TRequests_3TRequestStatuses", "C3TRequests")]
        public EntityCollection<C3TRequests> C3TRequests
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<C3TRequests>("TSTModel.FK_3TRequests_3TRequestStatuses", "C3TRequests");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<C3TRequests>("TSTModel.FK_3TRequests_3TRequestStatuses", "C3TRequests", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
